# Generated by Django 4.1.5 on 2023-02-02 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0008_auto_20191202_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='priority',
            field=models.IntegerField(choices=[('Most', 0), ('More', 1), ('Moderate', 2), ('Less', 3), ('Least', 4), ('Null', 5)], default=5),
        ),
    ]
