# Generated by Django 4.1.5 on 2023-02-02 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0009_todo_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.IntegerField(choices=[(0, 'Most'), (1, 'More'), (2, 'Moderate'), (3, 'Less'), (4, 'Least'), (5, 'Null')], default=5),
        ),
    ]
